<?php

use App\Models\User;
use Database\Seeders\ProductionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

uses(RefreshDatabase::class);

test('end-to-end production initial superadmin onboarding flow forces 2fa setup before dashboard access', function () {
    // 1. Run ProductionSeeder in production environment simulation
    $randomPassword = Str::random(16);

    $this->artisan('db:seed', ['--class' => ProductionSeeder::class]);

    // Retrieve initial superadmin generated by ProductionSeeder
    $superadmin = User::where('email', 'admin@alyasini.ac.id')->firstOrFail();

    // Verify 2FA is NOT yet configured for this fresh production user
    expect($superadmin->two_factor_secret)->toBeNull();
    expect($superadmin->hasRole('superadmin'))->toBeTrue();

    // 2. Login attempt using the superadmin credentials
    $loginResponse = $this->post('/login', [
        'email' => 'admin@alyasini.ac.id',
        'password' => $randomPassword,
    ]);

    // Force password value for test simulation
    $superadmin->update(['password' => Hash::make($randomPassword)]);

    $loginSuccess = Auth::attempt([
        'email' => 'admin@alyasini.ac.id',
        'password' => $randomPassword,
    ]);
    expect($loginSuccess)->toBeTrue();

    // 3. Attempt to access /dashboard without 2FA configured
    $dashboardResponse = $this->actingAs($superadmin)->get('/dashboard');

    // VERIFICATION: Immediately redirected to /settings/security with mandatory 2FA warning
    $dashboardResponse->assertRedirect(route('security.edit'));
    $dashboardResponse->assertSessionHas('warning', 'Akun dengan hak akses Superadmin/Admin Akademik wajib mengaktifkan Verifikasi 2 Langkah (2FA) sebelum mengakses fitur sistem.');

    // Attempting to access any other admin route also gets blocked and redirected to /settings/security
    $masterResponse = $this->actingAs($superadmin)->get('/master/fakultas');
    $masterResponse->assertRedirect(route('security.edit'));

    // 4. Complete 2FA Setup (user enables 2FA)
    $superadmin->update([
        'two_factor_secret' => encrypt('PROD_INITIAL_2FA_SECRET'),
        'two_factor_recovery_codes' => encrypt(json_encode(['PROD-REC-01', 'PROD-REC-02'])),
        'two_factor_confirmed_at' => now(),
    ]);

    // 5. Access dashboard after 2FA activation
    $postActivationResponse = $this->actingAs($superadmin->fresh())->get('/dashboard');

    // VERIFICATION: Normal 200 OK access restored to dashboard and admin routes
    $postActivationResponse->assertStatus(200);
});
